plugins: rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
Documentation:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/**
    - db/schema.rb
    - db/queue_schema.rb
